{{- if .Values.jxInstall.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: jx-install
  namespace: jx-git-operator
  annotations:
    docs.jenkins-x.io: https://jenkins-x.io/v3/admin/troubleshooting/install/
spec:
  runInterval: {{ .Values.jxInstall.runInterval }}
  timeout: {{ .Values.jxInstall.timeout }}
  podSpec:
    containers:
      - name: jx-install
        image: {{ .Values.jxInstall.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            cpu: 25m
            memory: 15Mi
          limits:
            cpu: 40m
    restartPolicy: Never
    serviceAccountName: jx-install-sa
    terminationGracePeriodSeconds: 60
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jx-install-check-rb
  namespace: jx-git-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jx-install-service-role
subjects:
  - kind: ServiceAccount
    name: jx-install-sa
    namespace: jx-git-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jx-install-service-role
  namespace: jx-git-operator
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-install-sa
  namespace: jx-git-operator

{{- end }}