{{- if .Values.jxWebhooks.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: jx-webhook
  namespace: jx
  annotations:
    docs.jenkins-x.io: https://jenkins-x.io/v3/admin/troubleshooting/webhooks/
spec:
  runInterval: {{ .Values.jxWebhooks.runInterval }}
  timeout: {{ .Values.jxWebhooks.timeout }}
  podSpec:
    containers:
      - name: jx-webhook
        image: {{ .Values.jxWebhooks.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            cpu: 25m
            memory: 15Mi
          limits:
            cpu: 40m
    restartPolicy: Never
    serviceAccountName: jx-webhook-sa
    terminationGracePeriodSeconds: 60
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jx-webhook-check-rb
  namespace: jx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jx-webhook-service-role
subjects:
  - kind: ServiceAccount
    name: jx-webhook-sa
    namespace: jx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jx-webhook-service-role
  namespace: jx
rules:
  - apiGroups:
      - "jenkins.io"
    resources:
      - sourcerepositories
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-webhook-sa
  namespace: jx

{{- end }}